allvars<-c("ID",
"sex",
"ethnicity",
"ever_drank_alc",
"most_drinks_24hr2",
strong_desire_alc
tolerance_alc
want_to_stop_alc
more_than_intended_alc
drunk_didnt_want_alc
reduced_activities_alc
so_much_time_alc
despite_problems_alc
withdrawal_alc
drink_mother
drink_father
drink_family
drugs_family
peers_cigarettes
peers_got_drunk
peers_alc_probs
peers_drank_alc
peers_trouble_law
peers_stole
peers_cut_class
peers_cheated
peers_marijuana
peers_inhalants
peers_other_drugs
peers_sold_drug
lifetime_cig
frequency_hookah
cannabis_ever
sedatives_ever
stimulants_ever
cocaine_ever
opioids_ever
"Extraversion",
"Agreeableness",
"Conscientiousness",
"Neuroticism",
"Openness",
"Sexuality",
"Impairment",
"Risk and Aggression",
"Tension Reduction",
"Liquid_Courage",
"Self_Perception",
"Sociability",
"social_drinking",
"conformity_drinking",
"drinking_cope",
"drinking_enhance",
"PGD_tot",
"anx_sx",
"dep_sx",
"Freq_quant")